In [1]:
import numpy as np

In [2]:
# Creating a numpy array
arr = np.array([1, 2, 3, 4, 5 ])
print(arr)

[1 2 3 4 5]


In [3]:
# Create an array with 9 zeros
zeros = np.zeros(9)
print(zeros)
print(len(zeros))

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
9


In [4]:
# Create an array with 100 ones
ones = np.ones(100)
print(ones)
print(len(ones))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
100


In [5]:
# Correcting the matrix to have equal-length rows
matrix = np.array([[1, 2, 3], [4, 5, 6]]) # indicates two rows and three columns 

print("Shape of matrix before applying reshape function:", matrix.shape)
matrix_reshaped = np.reshape(matrix, (3, 2))
print("Shape of matrix after applying reshape function:", matrix_reshaped.shape)

Shape of matrix before applying reshape function: (2, 3)
Shape of matrix after applying reshape function: (3, 2)


In [6]:
# Joining two arrays
matrix1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
matrix2 = np.array([[9, 10, 11 ,12], [13, 14, 15, 16]])
print(matrix1)
print("------------------")
print(matrix2)
print("------------------")
matrix3 = np.concatenate((matrix1, matrix2), axis = 1) # column wise
print(matrix3)
print("------------------")
matrix4 = np.concatenate((matrix1, matrix2), axis = 0) # row wise
print(matrix4)

[[1 2 3 4]
 [5 6 7 8]]
------------------
[[ 9 10 11 12]
 [13 14 15 16]]
------------------
[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]
------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
# Finding mean in an array/matrix
seq = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9 ,10])
print(seq.mean())

5.5


In [8]:
# Finding the sum in an array/matrix
print(seq.sum())

55


In [9]:
# Finding the min in an array/matrix
seq2 = np.array([[1, 2, 3, 4], [5, 0, 10, 9]])
print(seq2.min())

0


In [10]:
# Finding the max in an array/matrix
print(seq2.max())

10


In [11]:
# Finding the index of the max value
seq3 = np.matrix([[1,200,3,33],[4,5,6,66],[7,8,9,99]])
print(np.argmax(seq3, axis = 1)) # returns index of the max value in each column

[[1]
 [3]
 [3]]


In [12]:
# Finding the index of the min value\
seq3 = np.matrix([[10,200,3,33],[4,5,6,66],[7,8,9,99]])
print(np.argmin(seq3, axis = 1)) # returns index of the min value in each column

[[2]
 [0]
 [0]]


In [13]:
# Creating a random array with random floats
random_arr = np.random.rand(3, 5)
print(random_arr)

[[0.88872671 0.64148689 0.11741628 0.97250557 0.22898795]
 [0.1232381  0.56653075 0.41946965 0.1273502  0.36796165]
 [0.60315349 0.43477454 0.02260687 0.32108343 0.9605094 ]]


In [14]:
# Creating or samples from the “standard normal” distribution.
random_gauss = np.random.randn(3, 5)
print(random_gauss)

[[ 0.06980241 -0.1938083   0.2764738  -0.87408946 -1.32524406]
 [ 0.99475427  1.08538272 -0.25787741  0.84705699 -0.40900987]
 [ 1.38960066 -0.59740429 -0.19186128  0.17031976  0.40338161]]


In [15]:
# Creating random intergers between limits 4.5 and 10.9
rand_ints = np.random.randint(low = 4.5,high = 10.9, size = 10 )
print(rand_ints)

[8 8 4 8 5 4 9 4 5 8]


In [16]:
# taking dot product of two vectors
a = 2 + 33j
b = 14 + 5j
print(np.dot(a, b)) # 2(14 + 5j) + 33j(14 +5j)

(-137+472j)
