In [1]:
import numpy as np

In [2]:
# Creating a numpy array
arr = np.array([1, 2, 3, 4, 5 ])
print(arr)

[1 2 3 4 5]


In [3]:
# Create an array with 9 zeros
zeros = np.zeros(9)
print(zeros)
print(len(zeros))

[0. 0. 0. 0. 0. 0. 0. 0. 0.]
9


In [4]:
# Create an array with 100 ones
ones = np.ones(100)
print(ones)
print(len(ones))

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.
 1. 1. 1. 1.]
100


In [5]:
# Correcting the matrix to have equal-length rows
matrix = np.array([[1, 2, 3], [4, 5, 6]]) # indicates two rows and three columns 

print("Shape of matrix before applying reshape function:", matrix.shape)
matrix_reshaped = np.reshape(matrix, (3, 2))
print("Shape of matrix after applying reshape function:", matrix_reshaped.shape)

Shape of matrix before applying reshape function: (2, 3)
Shape of matrix after applying reshape function: (3, 2)


In [6]:
# Joining two arrays
matrix1 = np.array([[1, 2, 3, 4], [5, 6, 7, 8]])
matrix2 = np.array([[9, 10, 11 ,12], [13, 14, 15, 16]])
print(matrix1)
print("------------------")
print(matrix2)
print("------------------")
matrix3 = np.concatenate((matrix1, matrix2), axis = 1) # column wise
print(matrix3)
print("------------------")
matrix4 = np.concatenate((matrix1, matrix2), axis = 0) # row wise
print(matrix4)

[[1 2 3 4]
 [5 6 7 8]]
------------------
[[ 9 10 11 12]
 [13 14 15 16]]
------------------
[[ 1  2  3  4  9 10 11 12]
 [ 5  6  7  8 13 14 15 16]]
------------------
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [7]:
# Finding mean in an array/matrix
seq = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9 ,10])
print(seq.mean())

5.5


In [8]:
# Finding the sum in an array/matrix
print(seq.sum())

55


In [9]:
# Finding the min in an array/matrix
seq2 = np.array([[1, 2, 3, 4], [5, 0, 10, 9]])
print(seq2.min())

0


In [10]:
# Finding the max in an array/matrix
print(seq2.max())

10


In [11]:
# Finding the index of the max value
seq3 = np.matrix([[1,200,3,33],[4,5,6,66],[7,8,9,99]])
print(np.argmax(seq3, axis = 1)) # returns index of the max value in each column

[[1]
 [3]
 [3]]


In [12]:
# Finding the index of the min value\
seq3 = np.matrix([[10,200,3,33],[4,5,6,66],[7,8,9,99]])
print(np.argmin(seq3, axis = 1)) # returns index of the min value in each column

[[2]
 [0]
 [0]]


In [13]:
# Creating a random array with random floats
random_arr = np.random.rand(3, 5)
print(random_arr)

[[0.04920526 0.76400429 0.78181321 0.86225451 0.01938729]
 [0.19322047 0.89952687 0.93889095 0.95817125 0.17439809]
 [0.53866542 0.55604439 0.12462593 0.62111243 0.39522214]]


In [14]:
# Creating or samples from the “standard normal” distribution.
random_gauss = np.random.randn(3, 5)
print(random_gauss)

[[ 2.21765804  0.82411185 -0.9520953   0.73368041  0.71648607]
 [-0.60274055 -0.7862422  -3.12504934  2.06748033  0.37407877]
 [-1.65794197 -0.91645635  0.41150848  1.07670262  1.14339103]]


In [15]:
# Creating random intergers between limits 4.5 and 10.9
rand_ints = np.random.randint(low = 4.5,high = 10.9, size = 10 )
print(rand_ints)

[4 5 4 8 4 5 4 9 9 7]


In [17]:
# taking dot product of two vectors
a = 2 + 33j
b = 14 + 5j
print(np.dot()

TypeError: 'builtin_function_or_method' object is not subscriptable